/**
 * Files we touch in the dev's home directory:
 *
 *   ~/.platform/env                   — `export PLATFORM_NPM_TOKEN=…`
 *                                       (and the platform URLs so new
 *                                       shells don't have to know them)
 *   ~/.zshrc / ~/.bashrc              — sentinel-bracketed block that
 *                                       sources ~/.platform/env, adds
 *                                       ~/.platform/bin to PATH, and
 *                                       activates mise so the pinned
 *                                       Node 22 + pnpm versions are on
 *                                       PATH for every new shell
 *
 * Idempotency is non-negotiable: every CLI command can be run multiple
 * times, and the user's rc files must end up the same regardless. We
 * use a sentinel comment so we can detect a previous insertion without
 * relying on exact-string matching (lets the user reorder lines). On
 * re-run we replace the bracketed block in place rather than appending
 * a duplicate.
 */

import {
  appendFileSync,
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { execFileSync } from "node:child_process";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

const SENTINEL_START = "# >>> platform-cli managed >>>";
const SENTINEL_END = "# <<< platform-cli managed <<<";

/** Effective home directory. Prefers `process.env.HOME` over `os.homedir()`
 * because vitest workers on some Linux CI images don't propagate env-var
 * changes into libuv's homedir lookup, even though Node docs say
 * `uv_os_homedir` reads `HOME` first. Belt-and-suspenders. */
function effectiveHome(): string {
  return process.env.HOME ?? process.env.USERPROFILE ?? homedir();
}

export function platformEnvPath(home: string = effectiveHome()): string {
  return join(home, ".platform", "env");
}

export interface PlatformEnv {
  /** The dev's developer git token. */
  token: string;
  /** Per-platform git/npm proxy host, used by the cred-helper and CLI. */
  proxyBaseUrl?: string;
  /** App-store host, used by `platform login` for SSO redirect. */
  appStoreUrl?: string;
  /** API-gateway host, used by the CLI for token mint + dev/skills. */
  apiGatewayUrl?: string;
}

/** Write `~/.platform/env` with PLATFORM_NPM_TOKEN plus (optionally) the
 * three host URLs so subsequent shells don't have to know them. The
 * file is mode 0600 — it contains a long-lived credential.
 *
 * Backwards-compatible: callers that only pass a token (the legacy
 * shape) still work.
 */
export function writePlatformEnv(
  envOrToken: PlatformEnv | string,
  home: string = effectiveHome(),
): string {
  const env: PlatformEnv =
    typeof envOrToken === "string" ? { token: envOrToken } : envOrToken;
  const path = platformEnvPath(home);
  mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
  const lines: string[] = [
    "# Generated by `platform login` — do not edit by hand.",
    "# Re-run `platform refresh` to rotate the token.",
    `export PLATFORM_NPM_TOKEN=${shellEscape(env.token)}`,
  ];
  if (env.proxyBaseUrl) {
    lines.push(`export PLATFORM_PROXY_BASE_URL=${shellEscape(env.proxyBaseUrl)}`);
  }
  if (env.appStoreUrl) {
    lines.push(`export APP_STORE_URL=${shellEscape(env.appStoreUrl)}`);
  }
  if (env.apiGatewayUrl) {
    lines.push(`export API_GATEWAY_URL=${shellEscape(env.apiGatewayUrl)}`);
  }
  writeFileSync(path, `${lines.join("\n")}\n`, { mode: 0o600 });
  chmodSync(path, 0o600);
  return path;
}

/** Detect mise on PATH. Without it we skip the `mise activate` snippet
 * — the user can still build, just on whatever Node they have system-wide. */
function miseAvailable(): boolean {
  try {
    execFileSync("mise", ["--version"], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

/** Build the rc-file managed block. Per-shell because `mise activate`
 * needs the shell name. */
function managedBlock(shell: "zsh" | "bash"): string {
  const lines = [
    SENTINEL_START,
    'export PATH="$HOME/.platform/bin:$PATH"',
    '[ -f "$HOME/.platform/env" ] && . "$HOME/.platform/env"',
  ];
  if (miseAvailable()) {
    lines.push(`command -v mise >/dev/null 2>&1 && eval "$(mise activate ${shell})"`);
  }
  lines.push(SENTINEL_END);
  return `\n${lines.join("\n")}\n`;
}

/** Append (or replace, if already present) the managed snippet in
 * `~/.zshrc` and `~/.bashrc`. Returns the list of files edited.
 *
 * The block is bracketed by sentinel comments so re-runs replace it in
 * place — important because we add lines to it over time (originally
 * just env-sourcing; later mise-activation), and we don't want stale
 * versions to accumulate. */
export function ensureShellRcSourcesEnv(home: string = effectiveHome()): string[] {
  const candidates: { path: string; shell: "zsh" | "bash" }[] = [
    { path: join(home, ".zshrc"), shell: "zsh" },
    { path: join(home, ".bashrc"), shell: "bash" },
  ];
  const edited: string[] = [];
  for (const { path, shell } of candidates) {
    if (!existsSync(path)) continue;
    const existing = readFileSync(path, "utf8");
    const block = managedBlock(shell);

    if (existing.includes(SENTINEL_START)) {
      // Replace the existing block in place — keeps re-runs idempotent
      // even when our snippet content evolves.
      const re = new RegExp(
        `\\n?${escapeRe(SENTINEL_START)}[\\s\\S]*?${escapeRe(SENTINEL_END)}\\n?`,
      );
      const updated = existing.replace(re, block);
      if (updated !== existing) {
        writeFileSync(path, updated);
        edited.push(path);
      }
    } else {
      appendFileSync(path, block);
      edited.push(path);
    }
  }
  return edited;
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Quote a string for safe inclusion in a POSIX shell single-quoted
 * literal. */
function shellEscape(value: string): string {
  // Wrap in single quotes; escape any embedded single quotes via
  // '"'"' which is the canonical POSIX escape.
  return `'${value.replace(/'/g, "'\\''")}'`;
}
