/**
 * Files we touch in the dev's home directory:
 *
 *   ~/.platform/env                   — `export PLATFORM_NPM_TOKEN=…`
 *   ~/.zshrc / ~/.bashrc              — append `[ -f ~/.platform/env ]
 *                                        && . ~/.platform/env` once
 *
 * Idempotency is non-negotiable: every CLI command can be run multiple
 * times, and the user's rc files must end up the same regardless. We
 * use a sentinel comment so we can detect a previous insertion without
 * relying on exact-string matching (lets the user reorder lines).
 */

import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

const SENTINEL = "# >>> platform-cli managed >>>";
const SENTINEL_END = "# <<< platform-cli managed <<<";
const SOURCE_LINE = "[ -f \"$HOME/.platform/env\" ] && . \"$HOME/.platform/env\"";

/** Effective home directory. Prefers `process.env.HOME` over `os.homedir()`
 * because vitest workers on some Linux CI images don't propagate env-var
 * changes into libuv's homedir lookup, even though Node docs say
 * `uv_os_homedir` reads `HOME` first. Belt-and-suspenders. */
function effectiveHome(): string {
  return process.env.HOME ?? process.env.USERPROFILE ?? homedir();
}

export function platformEnvPath(home: string = effectiveHome()): string {
  return join(home, ".platform", "env");
}

/** Write `~/.platform/env` with a single PLATFORM_NPM_TOKEN export.
 * The file is mode 0600 (it contains a long-lived credential). */
export function writePlatformEnv(token: string, home: string = effectiveHome()): string {
  const path = platformEnvPath(home);
  mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
  const body = `# Generated by \`platform login\` — do not edit by hand.
# Re-run \`platform refresh\` to rotate.
export PLATFORM_NPM_TOKEN=${shellEscape(token)}
`;
  writeFileSync(path, body, { mode: 0o600 });
  chmodSync(path, 0o600);
  return path;
}

/** Append the sourcing snippet to `~/.zshrc` and `~/.bashrc` if it isn't
 * already there. Returns the list of files we edited. */
export function ensureShellRcSourcesEnv(home: string = effectiveHome()): string[] {
  const candidates = [
    join(home, ".zshrc"),
    join(home, ".bashrc"),
  ];
  const edited: string[] = [];
  for (const path of candidates) {
    if (!existsSync(path)) continue;
    const existing = readFileSync(path, "utf8");
    if (existing.includes(SENTINEL)) continue;
    appendFileSync(path, `\n${SENTINEL}\n${SOURCE_LINE}\n${SENTINEL_END}\n`);
    edited.push(path);
  }
  return edited;
}

/** Quote a string for safe inclusion in a POSIX shell single-quoted
 * literal. */
function shellEscape(value: string): string {
  // Wrap in single quotes; escape any embedded single quotes via
  // '"'"' which is the canonical POSIX escape.
  return `'${value.replace(/'/g, "'\\''")}'`;
}
